# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6293a4d0a7228ab1f47eb6227d0180854b34ea4774ff29dcdbef49e585bd4649e365f5c526c8d9e5c5819f4f76f36ff1c53754f665d50153a508db6b924ec4f2

test:
  secret_key_base: beb764a1f50ba03558779f238173de95ef2a6cf4611d7f202e0fd767c8ce339455ccd19d3df9fa1ce5840dc4c2342013604f75f0c169268a869fbc09e9c2331d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
